# -*- coding: utf-8 -*-
"""Text summarization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hl7EWJsXu8kLg5jr-3TFCHZimiOnJp4f
"""

!pip install flask pyngrok transformers torch newspaper3k lxml[html5] lxml_html_clean

!mkdir -p templates
!mkdir -p static
!mkdir -p uploads

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# from flask import Flask, render_template, request
# from transformers import pipeline
# from newspaper import Article
# import os
# 
# app = Flask(__name__)
# 
# # ------------------- Load Summarization Model -------------------
# summarizer = pipeline("summarization", model="facebook/bart-large-cnn")
# 
# def summarize_text_or_url(input_text=None, input_url=None):
#     if input_url:
#         article = Article(input_url)
#         article.download()
#         article.parse()
#         text = article.text
#     elif input_text:
#         text = input_text
#     else:
#         return "❗ Please provide text or a URL."
# 
#     summary = summarizer(text, max_length=150, min_length=50, do_sample=False)
#     return summary[0]['summary_text']
# 
# 
# @app.route("/", methods=["GET", "POST"])
# def home():
#     summary = ""
#     input_text = ""
#     input_url = ""
# 
#     if request.method == "POST":
#         input_text = request.form.get("input_text")
#         input_url = request.form.get("input_url")
# 
#         summary = summarize_text_or_url(input_text=input_text, input_url=input_url)
# 
#     return render_template("index.html", summary=summary, input_text=input_text, input_url=input_url)
# 
# 
# if __name__ == "__main__":
#     app.run(host="0.0.0.0", port=8000, debug=False)
# 
#

"""# HTML"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile templates/index.html
# <!DOCTYPE html>
# <html>
# <head>
#     <title>📰 Text & URL Summarizer</title>
#     <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
# </head>
# <body>
# <div class="container">
#     <h1>📰 Text & URL Summarizer</h1>
# 
#     <div class="card">
#         <h2>Enter Text</h2>
#         <form method="post">
#             <textarea name="input_text" placeholder="Paste text here..." rows="6">{{ input_text }}</textarea>
#             <h3>OR</h3>
#             <input type="url" name="input_url" placeholder="Enter article URL" value="{{ input_url }}">
#             <button type="submit">Summarize 🚀</button>
#         </form>
#     </div>
# 
#     {% if summary %}
#     <div class="card">
#         <h2>Summary</h2>
#         <p>{{ summary }}</p>
#     </div>
#     {% endif %}
# </div>
# </body>
# </html>

# Commented out IPython magic to ensure Python compatibility.
# %%writefile static/style.css
# body {
#     font-family: 'Segoe UI', sans-serif;
#     background: linear-gradient(135deg, #0f2027, #203a43, #2c5364);
#     color: white;
#     display: flex;
#     justify-content: center;
#     align-items: center;
#     height: 100vh;
#     margin: 0;
# }
# .container {
#     text-align: center;
#     width: 60%;
# }
# h1, h2, h3 {
#     margin-bottom: 15px;
# }
# .card {
#     background: rgba(255, 255, 255, 0.1);
#     padding: 20px;
#     border-radius: 12px;
#     box-shadow: 0 0 15px rgba(0,0,0,0.4);
#     margin-bottom: 20px;
# }
# textarea, input, button {
#     width: 90%;
#     margin: 10px 0;
#     padding: 10px;
#     border-radius: 8px;
#     border: none;
# }
# textarea {
#     resize: vertical;
# }
# button {
#     background: #FFD700;
#     cursor: pointer;
#     font-weight: bold;
# }
# button:hover {
#     background: #FFA500;
# }

!pkill -f flask || echo "No flask running"
!pkill -f ngrok || echo "No ngrok running"

!lsof -i : 8000

!kill -9 1144

!nohup python app.py > flask.log 2>&1 &

from pyngrok import ngrok, conf
conf.get_default().auth_token = "32rscLFLHDJnxKCvvA7VUhgIwAu_36nxu7tTVxR6mfaSa7hdB"
public_url = ngrok.connect(8000)
print("🌍 Public URL:", public_url)